/**
 * CONTENT-01｜第一包「Formal Fixed 真心话」正式内容源（C1-2 产出；**已接入生产链路，非「零引用」**）。
 *
 * ## 现状（C1-2 之后各单已落地，本源已真正生效）
 * 本文件导出 `FORMAL_TRUTH_CARDS`（24 张 `PN-TRUTH-201~224`），当前被以下位置 import：
 * - `lib/v2-content/v2-card-bridge.ts`（C1-3 桥接）：`mainlineSsotCards()` 在既有 350 张**之后
 *   追加**本包，`mainlineRuntimeCards()` / `mainlineCardMetaById()` 共用同一份卡源；
 * - `lib/v2-content/v2-card-quality-index.ts`（C1-4 质量侧车）；
 * - `scripts/audit-bar-fit-human-review-skeleton.ts` / `scripts/audit-formal-truth-selfcheck.ts`（C1-6）；
 * - `tests/unit/*`（formal-truth-pipeline / fixed-content-manifest / v2-b7-content-switch 等）。
 * 经构建期准入（`pnpm build:fixed-manifest`）后进入 `tracks.formalFixed`；当前值见产物。
 *
 * ## C1-2 当时范围说明（历史注记，非现状）
 * 本单只产出**内容**：一批带完整 Plan §3 质量字段的真心话卡（`PN-TRUTH-2xx`）。当时本文件
 * **不被任何文件 import**——桥接（C1-3）、质量侧车（C1-4）、人审输入（C1-5）、审查脚本（C1-6）、
 * 单包 Monte Carlo（C1-7）都是后续单，落地后本源才真正生效；故当时业务行为变化为 **0**，
 * 既有 390 张卡与冻结 SSOT 零改动（至今 SSOT 仍零改动）。
 *
 * ## 为什么另起内容源，而不是改既有 390 卡（C1-1 设计稿 §2.2/§9 的结论）
 * - 冻结 SSOT（`generated/v2-ssot.generated.json`，两个硬编码 SHA256）是唯一真源，不得就地改；
 * - 生产 Heat 恒 H1（disclosure 通道未落地 ⇒ 有效轮恒 0），**任何 `heatMin≥2` 的 Formal 卡
 *   在运行时都抽不到**。若把既有 `PN-TRUTH-*` 改判 Formal，等于把那批卡从可玩库存里删掉，
 *   会重演刚修好的「H1 桶耗尽 / PACK_EXHAUSTED」。
 * - 故第一包走「**新 ID + 全部 `heatMin=1` + 独立正式内容源**」，既有 390 卡一张不动。
 *
 * ## ID 约定
 * - 前缀沿用 `PN-TRUTH`（既有 pack / gameType 映射表 `V2_MAINLINE_PACK_BY_GAME_TYPE` 已认它）；
 * - 编号取 `201~224`，与既有 `PN-TRUTH-001~050` **不重叠**，全库唯一性可机械核验；
 * - `number` 与 ID 末段同值（201~224），不与既有 1~50 冲突。
 *
 * ## 逐条硬规格（Human + C1-1 设计稿，实现时逐条对齐）
 * 1. **玩法**：`gameType="truth"` → pack `truth-dare`（真心话）。
 * 2. **`heatMin` 一律 = 1**：见上「H1 桶耗尽」原因；`heatMax` 按卡的关系深度拉开到 H1~H4
 *    （本包 H1 2 张 / H2 3 张 / H3 6 张 / H4 13 张），为将来 Heat 推进留库存。
 * 3. **`intensity` 覆盖 1~5**（I1 4 / I2 9 / I3 7 / I4 2 / I5 2）：I1/I2 足量供 ceiling=1/2 的桌，
 *    I3/I4/I5 亦各有多张，不做「只做低强度」。
 * 4. **8 项必填质量字段逐卡齐全**（`V2_REQUIRED_QUALITY_FIELDS`，真源 `v2-card-metadata.ts`）：
 *    `topic` / `barFit` / `informationGain` / `informationGoal` / `socialEnergy` /
 *    `relationshipProgression` / `intimacyClass` / `informationGoalType`；另逐卡附
 *    `secondaryTopics`（可选字段，本包全体给出，不计主主题配额）。
 *    `barFit` 恒 `"PASS"`（Plan §3:52：正式快照只允许 PASS）。
 * 5. **优先补 A.1 的 2 个零维度**：`吃醋·占有`(2) / `异性朋友边界`(2) / `前任态度`(2) /
 *    `底线·雷区`(2) 与 `人生目标·理想生活`(2)；并覆盖 `性观念·亲密态度`(2，I4/I5) 与
 *    `亲密边界`(1，I5)。生活向另覆盖兴趣爱好 / 生活方式 / 性格·习惯·小癖好 / 恋爱观 /
 *    择偶偏好 / 相处规则（含沟通冲突方式与安全感）。
 * 6. **题面口径**：全部是「今晚问得出口、对方答了就真的更了解他」的**本人自述**问题；
 *    不做现场评价、不做猜测、不写「你们觉得呢」式空话；不复述既有 350 题句式（见 C1-2 自检
 *    脚本 `scripts/audit-formal-truth-selfcheck.ts` 的重复/近似检查）。
 * 7. **内容安全**：不做露骨、不做强迫惩罚灌酒、不做隐私脱衣非自愿；I1~I3 不出现亲密/性内容，
 *    I4/I5 才触及亲密态度与边界，且全部 `consentMode="skip-anytime"`（卡面说明「不愿意可无惩罚跳过」）。
 * 8. **张数 18~24**：本包 24 张。宁少勿滥——每张都要求有真实信息增量（故 `informationGain`
 *    无 `zero`/`low`，`relationshipProgression` 无 `none`）。
 *
 * ## boundaryTags 口径（Plan §3.1，逐题只看「题面真实命中哪个用户开关」）
 * Plan §3.1 明令：泛标签 `relationship-sensitive` **不自动等于** `ex-partner`，
 * 「只有题面真实命中精确开关才写对应过滤标签」；且 `V2_BOUNDARY_TAG_CATALOG` 之外的语义标签
 * （`jealousy-possessiveness` / `opposite-sex-friends` / `bottom-line` / `intimacy-attitude` 等，
 * 见 `V2_CONTENT_SEMANTIC_TAGS`）**不是用户开关**，不得写进 `boundaryTags`。
 * 因此本包只用精确标签，逐条判定：
 * - `前任态度` 两题 → `["ex-partner"]`（Plan §4：所有前任相关题必须标 `ex-partner`）；
 * - 其余 22 题 → `[]`：`吃醋·占有` / `异性朋友边界` / `底线·雷区` / `亲密边界` / `性观念·亲密态度`
 *   在 Plan §3.1 中**没有**直连用户开关（属语义维度，由 `topic` 表达）；
 * - 本包无身体接触、无饮酒、无金额、无手机/相册、无拍摄、无陌生人、无账号交换 ⇒ 不标对应标签。
 *
 * ⚠️ 给 C1-3（桥接）的交接要求：`SSOT_BOUNDARY_TAG_MAP` 目前只登记泛 5 项，遇到 `ex-partner`
 * 会 **fail closed 抛错**。C1-3 必须把 §3.1 的精确 10 项补进映射（与 App `BoundaryTag` 同名同义，
 * 1:1 直映），**且不得**把 `relationship-sensitive` 继续自动映到 `ex-partner`（Plan §3.1 明文禁止）。
 *
 * 真源引用（只读，本文件不改任何真源）：
 * - `lib/v2-content/v2-types.ts`（SSOT 形状 18 字段 + 硬编码 schemaVersion）
 * - `lib/v2-content/v2-card-metadata.ts`（Plan §3 质量字段枚举 + 精确雷区全集）
 */

import type {
  V2BoundaryTagName,
  V2InformationGain,
  V2InformationGoalType,
  V2IntimacyClass,
  V2RelationshipProgression,
  V2SocialEnergy,
  V2Topic,
} from "./v2-card-metadata";
import { V2_SSOT_SCHEMA_VERSION, type V13MainlineCard } from "./v2-types";

/**
 * 第一包正式固定卡的完整形状：SSOT 形状 18 字段（`V13MainlineCard`）+ Plan §3 质量字段。
 *
 * 与 `V13MainlineCard` 的差异是三处**按 Plan 收紧/放宽**（其余字段一律原样继承，不另造）：
 * - `gameType` 收窄为 `"truth"`（本源只产真心话）；
 * - `barFit` 收窄为 `"PASS"`（Plan §3:52：正式快照只允许 PASS）；
 * - `boundaryTags` 换成 `V2_BOUNDARY_TAG_CATALOG`（Plan §3 该行写的就是「§3.1 精确枚举」）：
 *   `V13MainlineCard.boundaryTags` 只登记既有 SSOT 的泛 5 项，装不下 §3.1 的精确标签
 *   （如 `ex-partner`）。这里是**放宽类型**而不是改真源——`v2-types.ts` 一个字未动。
 * 其余质量字段显式声明为**必填**（`V2CardQualityMetadata` 里它们是可选的，旧卡可缺）；
 * `secondaryTopics` 虽为可选字段，本包逐卡给出，故在此也声明为必填（允许空数组）。
 */
export interface FormalTruthCard
  extends Omit<V13MainlineCard, "gameType" | "boundaryTags"> {
  gameType: "truth";
  /** Plan §3.1 精确雷区标签（全集 `V2_BOUNDARY_TAG_CATALOG`，未知 tag 须拒收）。 */
  boundaryTags: readonly V2BoundaryTagName[];
  /** 主主题（Plan §3:48：§4 的 13 个人物主题之一，或 `live_chemistry`；单一主主题）。 */
  topic: V2Topic;
  /** 酒吧适配正式定档；正式入库只允许 `PASS`（Plan §3:52）。 */
  barFit: "PASS";
  /** 信息增量（Plan §3:53）：本人作答后能复述「谁的什么」的档位。 */
  informationGain: V2InformationGain;
  /** Plan §3:54 一句可复述的目标陈述；禁止泛化「促进了解」。 */
  informationGoal: string;
  /** 现场社交能量（Plan §3:55）：评价/投票/指认带来的现场反应强度，与信息量分开计。 */
  socialEnergy: V2SocialEnergy;
  /** 关系推进（Plan §3:56）：none/open/deepen/clarify_boundary。 */
  relationshipProgression: V2RelationshipProgression;
  /** 亲密类别（Plan §3:57，三值互斥）。本包全是态度/自述题，故只出现 `none` / `attitude`。 */
  intimacyClass: V2IntimacyClass;
  /** 信息目标类型（Plan §3:58，主目标只取一个）。 */
  informationGoalType: V2InformationGoalType;
  /** Plan §3:60 可选次主题数组；本包逐卡给出，不计主主题配额。 */
  secondaryTopics: readonly V2Topic[];
}

/** 冻结 SSOT schema 版本；本源同步沿用（不新造版本号）。 */
const SCHEMA = V2_SSOT_SCHEMA_VERSION;

/**
 * 第一包真心话正式固定卡（24 张，`PN-TRUTH-201~224`，全部 `heatMin=1`）。
 *
 * 排序：按 `cardId` 升序（201 → 224）。桥接侧若追加进 `mainlineSsotCards()`，
 * **只能追加在末尾**（不得前置/重排，否则既有取 `[0]` 的测试与 E2E 会漂移）。
 */
export const FORMAL_TRUTH_CARDS: readonly FormalTruthCard[] = [
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-201",
    gameType: "truth",
    number: 201,
    text: "说一件你最近主动花时间去做的小事，具体到那件事本身。",
    intensity: 1,
    heatMin: 1,
    heatMax: 1,
    relationStage: "notice",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "disclosure",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: [],
    postAction: "none",
    topic: "兴趣爱好",
    barFit: "PASS",
    informationGain: "medium",
    informationGoal: "知道他自己主动投入时间做的是什么，而不是职业或身份标签",
    socialEnergy: "low",
    relationshipProgression: "open",
    intimacyClass: "none",
    informationGoalType: "self_preference",
    secondaryTopics: ["生活方式"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-202",
    gameType: "truth",
    number: 202,
    text: "有没有一个爱好你坚持了很多年？说说它现在还在给你什么。",
    intensity: 1,
    heatMin: 1,
    heatMax: 2,
    relationStage: "know",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "disclosure",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: [],
    postAction: "none",
    topic: "兴趣爱好",
    barFit: "PASS",
    informationGain: "medium",
    informationGoal: "听出他长期坚持的爱好，以及这件事当下对他还有什么用",
    socialEnergy: "low",
    relationshipProgression: "open",
    intimacyClass: "none",
    informationGoalType: "self_preference",
    secondaryTopics: ["生活方式"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-203",
    gameType: "truth",
    number: 203,
    text: "下班或放学到睡前，你一个人最固定的一段安排是什么？",
    intensity: 1,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "choose-opposite-sex",
    responseMode: "public",
    interactionType: "disclosure",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "生活方式",
    barFit: "PASS",
    informationGain: "medium",
    informationGoal: "知道他每天真实的生活节奏与独处安排",
    socialEnergy: "low",
    relationshipProgression: "open",
    intimacyClass: "none",
    informationGoalType: "self_preference",
    secondaryTopics: ["性格·习惯·小癖好"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-204",
    gameType: "truth",
    number: 204,
    text: "最近一次有人对你抱有期待，你照做了还是没照？当时怎么决定的。",
    intensity: 2,
    heatMin: 1,
    heatMax: 3,
    relationStage: "signal",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "disclosure",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "生活方式",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "听到他最近一次面对别人的期待时，具体是怎么做决定的",
    socialEnergy: "low",
    relationshipProgression: "deepen",
    intimacyClass: "none",
    informationGoalType: "self_preference",
    secondaryTopics: ["人生目标·理想生活"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-205",
    gameType: "truth",
    number: 205,
    text: "说一个小习惯，是熟人相处久了才会发现的。",
    intensity: 1,
    heatMin: 1,
    heatMax: 1,
    relationStage: "notice",
    targetMode: "choose-opposite-sex",
    responseMode: "public",
    interactionType: "disclosure",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: [],
    postAction: "none",
    topic: "性格·习惯·小癖好",
    barFit: "PASS",
    informationGain: "medium",
    informationGoal: "拿到一个只有熟人相处久了才会知道的生活小习惯",
    socialEnergy: "low",
    relationshipProgression: "open",
    intimacyClass: "none",
    informationGoalType: "self_preference",
    secondaryTopics: ["生活方式"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-206",
    gameType: "truth",
    number: 206,
    text: "你在什么状态下会变得不像平时的自己？说一个最近发生的事。",
    intensity: 2,
    heatMin: 1,
    heatMax: 2,
    relationStage: "know",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "disclosure",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: [],
    postAction: "none",
    topic: "性格·习惯·小癖好",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "找到他状态走样时的具体触发场景，而不是笼统的性格形容词",
    socialEnergy: "low",
    relationshipProgression: "open",
    intimacyClass: "none",
    informationGoalType: "self_preference",
    secondaryTopics: ["相处规则"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-207",
    gameType: "truth",
    number: 207,
    text: "伴侣半天没回你消息时，你一般会做什么？",
    intensity: 2,
    heatMin: 1,
    heatMax: 3,
    relationStage: "signal",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "disclosure",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "恋爱观",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "知道伴侣半天没回消息时，他一般会怎么做",
    socialEnergy: "low",
    relationshipProgression: "deepen",
    intimacyClass: "none",
    informationGoalType: "self_preference",
    secondaryTopics: ["吃醋·占有"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-208",
    gameType: "truth",
    number: 208,
    text: "你觉得关系里喜欢和合适各占几成？说说你为什么这么分。",
    intensity: 3,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "恋爱观",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "听出他把长期关系押在喜欢还是合适上",
    socialEnergy: "medium",
    relationshipProgression: "deepen",
    intimacyClass: "none",
    informationGoalType: "self_preference",
    secondaryTopics: ["择偶偏好"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-209",
    gameType: "truth",
    number: 209,
    text: "你会被哪种人吸引？说一个具体行为，别只给形容词。",
    intensity: 2,
    heatMin: 1,
    heatMax: 2,
    relationStage: "know",
    targetMode: "choose-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: [],
    postAction: "none",
    topic: "择偶偏好",
    barFit: "PASS",
    informationGain: "medium",
    informationGoal: "把择偶标准落成一个别人看得见的具体行为",
    socialEnergy: "low",
    relationshipProgression: "open",
    intimacyClass: "none",
    informationGoalType: "self_preference",
    secondaryTopics: ["恋爱观"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-210",
    gameType: "truth",
    number: 210,
    text: "闹别扭时你是当场说开还是先冷一冷？你希望对方怎么做？",
    intensity: 2,
    heatMin: 1,
    heatMax: 3,
    relationStage: "signal",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "相处规则",
    barFit: "PASS",
    informationGain: "medium",
    informationGoal: "知道他在冲突里的处理方式和对对方的具体期待",
    socialEnergy: "low",
    relationshipProgression: "open",
    intimacyClass: "none",
    informationGoalType: "relationship_rule",
    secondaryTopics: ["恋爱观"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-211",
    gameType: "truth",
    number: 211,
    text: "关系里有没有你绝对不能接受的相处方式？说清一条。",
    intensity: 3,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "相处规则",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "听到他关系规则里的硬边界，而不只是偏好",
    socialEnergy: "low",
    relationshipProgression: "clarify_boundary",
    intimacyClass: "none",
    informationGoalType: "relationship_rule",
    secondaryTopics: ["底线·雷区"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-212",
    gameType: "truth",
    number: 212,
    text: "你会在什么情况下吃醋？说一件真发生过的，别用看情况带过。",
    intensity: 2,
    heatMin: 1,
    heatMax: 3,
    relationStage: "signal",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "disclosure",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "吃醋·占有",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "拿到他吃醋的真实触发场景，而不是宽泛态度",
    socialEnergy: "medium",
    relationshipProgression: "open",
    intimacyClass: "none",
    informationGoalType: "boundary_attitude",
    secondaryTopics: ["恋爱观"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-213",
    gameType: "truth",
    number: 213,
    text: "另一半和异性单独吃饭，你能接受到哪一步？说出你的分界。",
    intensity: 3,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "吃醋·占有",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "听他讲出伴侣与异性相处时他能接受的具体分界",
    socialEnergy: "medium",
    relationshipProgression: "clarify_boundary",
    intimacyClass: "none",
    informationGoalType: "boundary_attitude",
    secondaryTopics: ["异性朋友边界"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-214",
    gameType: "truth",
    number: 214,
    text: "你有关系很好的异性朋友吗？你们会聊到什么深度？",
    intensity: 2,
    heatMin: 1,
    heatMax: 3,
    relationStage: "signal",
    targetMode: "choose-opposite-sex",
    responseMode: "public",
    interactionType: "disclosure",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "异性朋友边界",
    barFit: "PASS",
    informationGain: "medium",
    informationGoal: "知道他与异性朋友交往的边界和会聊到的深度",
    socialEnergy: "low",
    relationshipProgression: "open",
    intimacyClass: "none",
    informationGoalType: "boundary_attitude",
    secondaryTopics: ["相处规则"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-215",
    gameType: "truth",
    number: 215,
    text: "如果伴侣要你少和某个异性朋友来往，你会怎么办？说实话。",
    intensity: 3,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "异性朋友边界",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "听到伴侣与异性朋友冲突时他的真实取舍",
    socialEnergy: "low",
    relationshipProgression: "clarify_boundary",
    intimacyClass: "none",
    informationGoalType: "boundary_attitude",
    secondaryTopics: ["底线·雷区"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-216",
    gameType: "truth",
    number: 216,
    text: "上一段关系结束时，你花最久才想通的是哪一点？",
    intensity: 3,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "disclosure",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: ["ex-partner"],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "前任态度",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "从他的上一段关系里听到他自己总结出的那条结论",
    socialEnergy: "medium",
    relationshipProgression: "deepen",
    intimacyClass: "none",
    informationGoalType: "experience",
    secondaryTopics: ["恋爱观"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-217",
    gameType: "truth",
    number: 217,
    text: "什么时刻，上一段关系最容易又浮上来？说说那种时刻的样子。",
    intensity: 4,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "choose-opposite-sex",
    responseMode: "public",
    interactionType: "disclosure",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: ["ex-partner"],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "前任态度",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "知道他还没完全放下上一段关系的具体时刻与样子",
    socialEnergy: "low",
    relationshipProgression: "deepen",
    intimacyClass: "none",
    informationGoalType: "experience",
    secondaryTopics: ["恋爱观"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-218",
    gameType: "truth",
    number: 218,
    text: "关系里踩到哪条线，你会直接结束而不是再谈一次？说一条。",
    intensity: 2,
    heatMin: 1,
    heatMax: 3,
    relationStage: "signal",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "底线·雷区",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "拿到他愿意直接终止关系的那条硬线",
    socialEnergy: "medium",
    relationshipProgression: "clarify_boundary",
    intimacyClass: "none",
    informationGoalType: "boundary_attitude",
    secondaryTopics: ["恋爱观"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-219",
    gameType: "truth",
    number: 219,
    text: "你身上哪一点，是你希望对方永远不要拿来开玩笑的？",
    intensity: 3,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "底线·雷区",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "听到他不容被拿来开玩笑的那个自我敏感点",
    socialEnergy: "low",
    relationshipProgression: "clarify_boundary",
    intimacyClass: "none",
    informationGoalType: "boundary_attitude",
    secondaryTopics: ["相处规则"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-220",
    gameType: "truth",
    number: 220,
    text: "五年后理想的一天，从睁眼到睡前，你最想保住的是哪三段？",
    intensity: 2,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "人生目标·理想生活",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "听他描述想要的生活具体长什么样，而不是价值观口号",
    socialEnergy: "medium",
    relationshipProgression: "open",
    intimacyClass: "none",
    informationGoalType: "self_preference",
    secondaryTopics: ["恋爱观"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-221",
    gameType: "truth",
    number: 221,
    text: "你最想完成的一件事是什么？说说你已经为它做过的一步。",
    intensity: 3,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "人生目标·理想生活",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "知道他人生的核心目标，以及他是否已经真的在动",
    socialEnergy: "low",
    relationshipProgression: "deepen",
    intimacyClass: "none",
    informationGoalType: "self_preference",
    secondaryTopics: ["生活方式"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-222",
    gameType: "truth",
    number: 222,
    text: "在亲密关系里，哪件事你希望对方一定先问过你？说一条。",
    intensity: 5,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "亲密边界",
    barFit: "PASS",
    informationGain: "high",
    informationGoal: "听到他要求对方先征得同意的具体亲密边界",
    socialEnergy: "low",
    relationshipProgression: "clarify_boundary",
    intimacyClass: "attitude",
    informationGoalType: "boundary_attitude",
    secondaryTopics: ["性观念·亲密态度"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-223",
    gameType: "truth",
    number: 223,
    text: "亲密里，对方主动和自己留空间各占几成？说说你为什么这么分。",
    intensity: 4,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "system-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "性观念·亲密态度",
    barFit: "PASS",
    informationGain: "medium",
    informationGoal: "听到他在亲密里给「对方主动」和「自己留空间」各分几成，以及他为什么这么分",
    socialEnergy: "low",
    relationshipProgression: "open",
    intimacyClass: "attitude",
    informationGoalType: "sexual_attitude_self_disclosure",
    secondaryTopics: ["亲密边界"],
  },
  {
    schemaVersion: SCHEMA,
    cardId: "PN-TRUTH-224",
    gameType: "truth",
    number: 224,
    text: "如果你们对亲密的节奏不一致，你会怎么开口谈？说一句。",
    intensity: 5,
    heatMin: 1,
    heatMax: 4,
    relationStage: "continue",
    targetMode: "choose-opposite-sex",
    responseMode: "public",
    interactionType: "expression",
    consentMode: "skip-anytime",
    matchRequired: false,
    boundaryTags: [],
    fallbackPolicy: "skip-card",
    signalEffects: ["personal"],
    postAction: "none",
    topic: "性观念·亲密态度",
    barFit: "PASS",
    informationGain: "medium",
    informationGoal: "听到他面对亲密节奏分歧时会先开口讲的那一句话",
    socialEnergy: "medium",
    relationshipProgression: "deepen",
    intimacyClass: "attitude",
    informationGoalType: "sexual_attitude_self_disclosure",
    secondaryTopics: ["亲密边界"],
  },
];
